### ISSUE TITLE
creation des formulaires et  gestion des authentifications

### ISSUE THREAD

**Issue by 1Cryptify** [1Cryptify/KarburD#2]

**Comment by 1Cryptify** [comment]
Bonjour ou bonsoir
 la team

**Comment by 1Cryptify** [comment]
Efontse gère la base de données

**Comment by 1Cryptify** [comment]
Kountchou gère la Vue c'est à dire la page PHP du formulaire avec son CSS

**Comment by 1Cryptify** [comment]
Moi je vais me charger de la liaison entre les deux parties (Le contrôleur)

**Comment by skinlesss** [comment]
> Kountchou gère la Vue c'est à dire la page PHP du formulaire avec son CSS

Ok boss

**Comment by 1Cryptify** [comment]
> Efontse gère la base de données 

La base de données doit refléter le diagramme de classe qui à été fixé

**Comment by 1Cryptify** [comment]
> Efontse gère la base de données 

A la fin tu exporte et tu fais un depot en ligne pour que nous ayons tous les mêmes bases de données

**Comment by efontse** [comment]
ok boss
c'esr compris

**Comment by efontse** [comment]
je le fais de suite

**Comment by 1Cryptify** [comment]
Super

**Comment by 1Cryptify** [comment]
Personne n'a encore fait de push ?, j'ai besoin de vos codes pour créer le contrôleur

**Comment by 1Cryptify** [comment]
S'il vous plaît lorsque vous déposez dans le répertoire venez Ici notifier pour que les autres prennent directement le relais pour réaliser leurs tâches.
Je confirme pour EFONTSE✅, mais j'attends encore le code Php et css de la page de login (Kountchou 😕).

**Comment by skinlesss** [comment]
Dsl j'ai dû gérer un petit souci, j'ai pas encore créé la page, mais demain matin je t'envoie ça 🙏🏽

**Comment by 1Cryptify** [comment]
Ok bro, sans soucis

**Comment by 1Cryptify** [comment]
> Dsl j'ai dû gérer un petit souci, j'ai pas encore créé la page, mais demain matin je t'envoie ça 🙏🏽

Importe déjà la base de données là chez toi en local , j'ai fait pareil

**Comment by skinlesss** [comment]
> > Dsl j'ai dû gérer un petit souci, j'ai pas encore créé la page, mais demain matin je t'envoie ça 🙏🏽
> 
> Importe déjà la base de données là chez toi en local , j'ai fait pareil 

D'accord

**Comment by 1Cryptify** [comment]
> > > Dsl j'ai dû gérer un petit souci, j'ai pas encore créé la page, mais demain matin je t'envoie ça 🙏🏽
> > 
> > Importe déjà la base de données là chez toi en local , j'ai fait pareil 
> 
> D'accord 

Grand Boss, les congés sont finis et même la page de login y'a pas

**Comment by skinlesss** [comment]
J'ai envoyé noo

**Comment by 1Cryptify** [comment]
Quand vous envoyez il faut signaler 😪

**Comment by 1Cryptify** [comment]
![Screenshot_20240407-181844.jpg](https://github.com/1Cryptify/KarburD/assets/154860426/d3ceaa3f-db1a-4705-8ec8-afee393b68ed)

Utilisez les commandes, l'a au-moins je suis facilement au courant quand il y'a commit et push

**Comment by skinlesss** [comment]
D'accord

**Comment by 1Cryptify** [comment]
Bonjour la team, svp rendez vous sur la page des répertoires, j'ai ajouter un commentaire sur quelques commandes (4) sur lesquels nous allons travailler, étapes par étapes, 

Au début il faudra installer git sur votre machine et ajouter le token de votre compte git à votre Pc pour l'authentification (youtube où chat gpt peux vous guider là dessus)

**Comment by 1Cryptify** [comment]
cette tache s'est terminee avec succes, merci a toute l'equipe
